// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/23/2024, 12:04:15 AM
const configMerger = require("/home/kali/Documents/projects/Nuxt/my-portfolio/node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.1_magicast@0.3.5_rollup@4.21.2/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/home/kali/Documents/projects/Nuxt/my-portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kali/Documents/projects/Nuxt/my-portfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kali/Documents/projects/Nuxt/my-portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kali/Documents/projects/Nuxt/my-portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kali/Documents/projects/Nuxt/my-portfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kali/Documents/projects/Nuxt/my-portfolio/plugins/**/*.{js,ts,mjs}","/home/kali/Documents/projects/Nuxt/my-portfolio/composables/**/*.{js,ts,mjs}","/home/kali/Documents/projects/Nuxt/my-portfolio/utils/**/*.{js,ts,mjs}","/home/kali/Documents/projects/Nuxt/my-portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/kali/Documents/projects/Nuxt/my-portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/kali/Documents/projects/Nuxt/my-portfolio/app.config.{js,ts,mjs}"] }));

module.exports = config
